apiVersion: v1
kind: Service
metadata:
  name: mac-app
spec:
  selector:
    run: mac-app
  ports:
  - name: http 
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https 
    protocol: TCP
    port: 443
    targetPort: 443    
  type: LoadBalancer